# Generated by Django 4.1.7 on 2023-02-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("floors", "0002_spot"),
    ]

    operations = [
        migrations.AddField(
            model_name="spot",
            name="is_free",
            field=models.BooleanField(default=True),
        ),
    ]
