# Generated by Django 4.1.7 on 2023-02-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_account_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "Mensagem de erro customizada"},
                max_length=127,
                unique=True,
            ),
        ),
    ]
