# Generated by Django 4.1.6 on 2023-02-13 13:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="published_data",
            new_name="published_date",
        ),
    ]
