# Generated by Django 4.1.6 on 2023-02-06 12:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="user",
            new_name="user_id",
        ),
    ]
