# Generated by Django 4.1.7 on 2023-02-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="shift",
            field=models.CharField(
                choices=[
                    ("Matutino", "Morning"),
                    ("Vespertino", "Afternoon"),
                    ("Noturno", "Night"),
                    ("Não informado", "Default"),
                ],
                default="Não informado",
                max_length=50,
            ),
        ),
    ]
