# Generated by Django 4.1.7 on 2023-03-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0003_alter_vehicle_arrived_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
