# Generated by Django 4.1.6 on 2023-02-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_account_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
    ]
