# Generated by Django 4.1.6 on 2023-02-06 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("addresses", "0002_rename_user_address_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="user_id",
            new_name="user",
        ),
    ]
