# Generated by Django 4.1.7 on 2023-02-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_account_email_alter_account_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.EmailField(
                error_messages={
                    "blank": "blank error",
                    "unique": "Mensagem de erro customizada",
                },
                max_length=127,
                unique=True,
            ),
        ),
    ]
