# Generated by Django 4.1.7 on 2023-03-13 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_plate", models.CharField(max_length=10)),
                ("color", models.CharField(default=None, max_length=100)),
                ("arrived_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("amount_paid", models.IntegerField(default=None, null=True)),
                ("paid_at", models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
