# Generated by Django 4.1.6 on 2023-02-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_created_at_user_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favorite_season",
            field=models.CharField(
                choices=[
                    ("Verão", "Summer"),
                    ("Outono", "Autumn"),
                    ("Inverno", "Winter"),
                    ("Primavera", "Spring"),
                    ("Não especificado", "Default"),
                ],
                default="Não especificado",
                max_length=25,
            ),
        ),
    ]
