# Generated by Django 4.1.7 on 2023-02-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking_lots", "0002_parkinglot_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkinglot",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
